### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kiprasmel** [kiprasmel/cputils#1]
- [ ] create & run multiple input files

notes: might consider using a single file with separation symbols for simplicity (less files - easier to edit:D)

might be useful to have:
- a parallelization option (`-jX`)
	- a max time limit before timeout in case an input hogs

how would we output the results though? one-by-one?

- [ ] ability to create test cases / expected outputs

probably in the same input file

- [x] stdin by default 
	- [ ] handle saving stdin to INPUT_FILE (https://serverfault.com/a/156510/506302)
- [x] clipboard via `-c`
- [ ] think about `-f` and `-c` integration

maybe `-f -c` could use clipboard if file empty / clipboard doesn't match the latest input

- [x] make g++ default args configurable

- [x] pipe-able hashing function instead of reading from a filename

- [x] rewrite examples & update docs since so much changed:D

- [ ] for maintainers: make it easier to fall into "the pit of success" in regards to hashing and making sure we've considered all side effects

- [ ] configurable compiler so that we're not locked into `g++` (just provide a function to compile in the config, as always)

- [x] tests!
	- [x] badges near commands in README via CI to indicate if it currently passes tests 👀
